# Generated by Django 4.2.3 on 2023-09-23 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Posst',
            new_name='Post',
        ),
    ]
