# Generated by Django 4.2.3 on 2023-11-03 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_header',
            field=models.CharField(max_length=100),
        ),
    ]
